import { useRef, useState } from "react";
import type { ChatMessage, Citation, StructuredQueryResult } from "../api/types";
import { sendChatMessage } from "../api/client";

interface DisplayMessage extends ChatMessage {
  citations?: Citation[];
  uncertain?: boolean;
  degraded?: boolean;
  fallbackModel?: string | null;
  queryMode?: "graphrag" | "structured";
  sqlUsed?: string | null;
  structuredResult?: StructuredQueryResult | null;
}

export function ChatPanel({ jobId, onMessageSent }: { jobId: string; onMessageSent?: () => void }) {
  const [messages, setMessages] = useState<DisplayMessage[]>([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  const send = async () => {
    const text = input.trim();
    if (!text || sending) return;
    setInput("");
    const history: ChatMessage[] = messages.map(({ role, content }) => ({ role, content }));
    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setSending(true);
    try {
      const resp = await sendChatMessage(jobId, text, history);
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant", content: resp.answer, citations: resp.citations, uncertain: resp.uncertain,
          degraded: resp.degraded, fallbackModel: resp.fallback_model,
          queryMode: resp.query_mode, sqlUsed: resp.sql_used, structuredResult: resp.structured_result,
        },
      ]);
    } catch (e) {
      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: `Error: ${e instanceof Error ? e.message : "chat failed"}`, uncertain: true },
      ]);
    } finally {
      setSending(false);
      setTimeout(() => scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }), 50);
      // The backend records this turn onto job.agent_activity (GraphRAG Chat
      // Synthesizer) regardless of whether it succeeded -- but polling for
      // job updates stops once the job reaches "complete" (see Dashboard's
      // pollOnce), so without this the Agent Activity panel would never
      // learn a chat turn happened at all. One-off refresh, not continuous
      // polling -- pollOnce() only reschedules itself for jobs still
      // actively processing.
      onMessageSent?.();
    }
  };

  return (
    <div className="chat-panel">
      <div className="chat-messages" ref={scrollRef}>
        {messages.length === 0 && (
          <p className="muted">
            Ask questions about the analyzed documents — answers are grounded in the retrieved
            text and knowledge graph, with citations back to source files.
          </p>
        )}
        {messages.map((m, i) => (
          <div key={i} className={`chat-msg chat-msg-${m.role}`}>
            <div className="chat-msg-bubble">
              {m.queryMode === "structured" && (
                <span className="structured-flag" title="Answered by generating and running real SQL against this job's structured files (CSV/Excel/Database), instead of semantic search.">
                  🧮 structured query
                </span>
              )}
              {m.degraded && (
                <span className="degraded-flag" title="Neo4j was unreachable — answered from local text search only, without knowledge-graph reasoning.">
                  ⚡ text search only (graph unavailable)
                </span>
              )}
              {m.fallbackModel && (
                <span
                  className="fallback-flag"
                  title={`The usual chat model was unreachable — this answer was generated by ${m.fallbackModel} instead.`}
                >
                  🔀 answered via {m.fallbackModel}
                </span>
              )}
              {m.content}
              {m.uncertain && <span className="uncertain-flag">⚠ low confidence</span>}
            </div>
            {m.queryMode === "structured" && m.sqlUsed && (
              <div className="structured-query-block">
                <details className="structured-sql">
                  <summary>View generated SQL</summary>
                  <pre>{m.sqlUsed}</pre>
                </details>
                {m.structuredResult && m.structuredResult.headers.length > 0 && (
                  <div className="structured-result-wrap">
                    <table className="data-table">
                      <thead>
                        <tr>{m.structuredResult.headers.map((h, hi) => <th key={hi}>{h}</th>)}</tr>
                      </thead>
                      <tbody>
                        {m.structuredResult.rows.map((row, ri) => (
                          <tr key={ri}>{row.map((v, vi) => <td key={vi}>{v === "" ? "—" : v}</td>)}</tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
                {m.structuredResult?.truncated && (
                  <div className="structured-result-note">Showing first {m.structuredResult.row_count} rows only.</div>
                )}
              </div>
            )}
            {m.citations && m.citations.length > 0 && (
              <div className="chat-citations">
                {m.citations.map((c, ci) => (
                  <details key={ci} className="citation">
                    <summary>{c.source_file.split("/").pop()}{c.page ? ` p.${c.page}` : ""}</summary>
                    <p>{c.chunk_text}</p>
                  </details>
                ))}
              </div>
            )}
          </div>
        ))}
        {sending && <div className="chat-msg chat-msg-assistant"><div className="chat-msg-bubble typing">…</div></div>}
      </div>
      <div className="chat-input-row">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter") send(); }}
          placeholder="Ask about the extracted intelligence…"
        />
        <button className="btn-primary" onClick={send} disabled={sending || !input.trim()}>Send</button>
      </div>
    </div>
  );
}
